#resource/application.properties

# # Cấu hình kết nối cơ sở dữ liệu
# spring.datasource.url=jdbc:mysql://localhost:3306/qr_ordering_db?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh
# spring.datasource.username=root
# spring.datasource.password=12345
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect


# # Cấu hình PostgreSQL trên Vercel
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Cấu hình JPA
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update

# Cấu hình Hibernate
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE

# Cấu hình Redis Caching
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.cache.type=redis
spring.cache.redis.time-to-live=1h


# Cấu hình cổng và địa chỉ máy chủ
server.address=0.0.0.0
server.port=${PORT:8080}

# JWT
security.jwt.secret=${JWT_SECRET}
security.jwt.expiration-ms=86400000   

# Cấu hình thông báo lỗi
server.error.include-message=always
server.error.include-binding-errors=always
# ProblemDetail
spring.mvc.problemdetails.enabled=true

# Cấu hình upload file
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Cấu hình email (thay đổi theo nhà cung cấp dịch vụ email của bạn)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ===== Cấu hình Cloudinary =====
cloudinary.cloud_name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api_key=${CLOUDINARY_API_KEY}
cloudinary.api_secret=${CLOUDINARY_API_SECRET}

# Cấu hình URL cơ bản của ứng dụng
app.base-url=${APP_BASE_URL}
app.frontend.base-url=${APP_FRONTEND_BASE_URL}


