export const defaultSettings = {
  id: 1,
  version: 0,
  restaurantName: 'Sắc Màu Quán',
  restaurantAddress: '',
  restaurantPhone: '',
  restaurantEmail: '',
  logoUrl: '',
  taxPercent: 0,
  serviceChargePercent: 0,
  currency: 'VND',
  wifiName: '',
  wifiPassword: '',
  openingTime: '',
  closingTime: '',
  orderingEnabled: true,
  maintenanceMode: false,
  cashPaymentEnabled: true,
  onlinePaymentEnabled: true,
  paymentQrExpiresInMinutes: 20,
  autoConfirmOrders: false,
  kitchenOverdueThresholdMinutes: 20,
  showUnavailableItems: false,
  showRecommendations: true,
  showCombos: true,
  billTitle: 'HÓA ĐƠN THANH TOÁN',
  billFooterMessage: 'CẢM ƠN QUÝ KHÁCH & HẸN GẶP LẠI!',
  billPaperSize: '80',
  showWifiOnBill: true,
  autoPrintBill: true,
  newOrderNotificationEnabled: true,
  paymentNotificationEnabled: true,
  kitchenOverdueNotificationEnabled: true,
};

export const settingsCopy = {
  vi: {
    page: {
      title: 'Cài đặt hệ thống',
      subtitle: 'Cấu hình quán, thanh toán, menu khách, vận hành, hóa đơn và thông báo.',
    },
    tabs: {
      restaurant: 'Thông tin quán',
      payment: 'Thanh toán',
      customerMenu: 'Menu khách hàng',
      operation: 'Vận hành',
      bill: 'Hóa đơn',
      notifications: 'Thông báo',
      wifi: 'WiFi & QR',
      preferences: 'Cá nhân hóa',
    },
    actions: {
      save: 'Lưu thay đổi',
      uploadLogo: 'Tải logo lên',
      uploading: 'Đang tải lên',
    },
    success: {
      saved: 'Cấu hình hệ thống đã được cập nhật.',
      logoUploaded: 'Logo quán đã được cập nhật.',
    },
    errors: {
      load: 'Không thể tải cài đặt',
      invalidData: 'Dữ liệu chưa hợp lệ',
      restaurantNameRequired: 'Tên quán không được để trống.',
      paymentMethodRequired: 'Cần bật ít nhất một phương thức thanh toán.',
    },
    restaurant: {
      title: 'Thông tin quán',
      subtitle: 'Thông tin nhận diện và liên hệ hiển thị trong hệ thống.',
      identityTitle: 'Nhận diện & liên hệ',
      logoTitle: 'Logo quán',
      logoEmpty: 'Chưa có logo',
      displayTitle: 'Cấu hình hiển thị',
      name: 'Tên quán',
      nameHelp: 'Hiển thị ở trang gọi món và trên hóa đơn.',
      hotline: 'Hotline',
      hotlineHelp: 'Số điện thoại liên hệ của quán.',
      address: 'Địa chỉ',
      addressHelp: 'Hiển thị trên hóa đơn và các khu vực thông tin quán.',
      email: 'Email',
      emailHelp: 'Email liên hệ nội bộ hoặc công khai của quán.',
      currency: 'Tiền tệ',
      currencyHelp: 'Mã tiền tệ ISO, ví dụ VND.',
      logoUrl: 'Logo URL',
      logoUrlHelp: 'Có thể dán URL ảnh public hoặc tải file JPEG, PNG, WebP tối đa 5MB.',
      taxPercent: 'Thuế (%)',
      taxPercentHelp: 'Lưu cấu hình thuế để dùng cho luồng tính tiền hỗ trợ.',
      serviceChargePercent: 'Phí dịch vụ (%)',
      serviceChargePercentHelp: 'Lưu cấu hình phí dịch vụ của quán.',
    },
    payment: {
      title: 'Thanh toán',
      subtitle: 'Kiểm soát phương thức thanh toán và thời hạn QR PayOS.',
      methodsTitle: 'Phương thức được phép',
      cash: 'Thanh toán tiền mặt',
      cashDesc: 'Cho phép nhân viên xác nhận thanh toán tiền mặt tại quầy.',
      online: 'QR / PayOS',
      onlineDesc: 'Cho phép tạo mã QR chuyển khoản qua PayOS.',
      expiryTitle: 'Thời hạn thanh toán online',
      expiry: 'QR hết hạn sau (phút)',
      expiryHelp: 'Áp dụng cho giao dịch PayOS mới, từ 1 đến 120 phút.',
    },
    customerMenu: {
      title: 'Menu khách hàng',
      subtitle: 'Chọn nội dung xuất hiện trên trang gọi món bằng QR.',
      visibilityTitle: 'Nội dung hiển thị',
      unavailable: 'Hiển thị món hết hàng',
      unavailableDesc: 'Món vẫn xuất hiện với nhãn hết hàng và không thể thêm vào giỏ.',
      recommendations: 'Hiển thị món gợi ý',
      recommendationsDesc: 'Hiển thị khu vực gợi ý theo thời điểm và lịch sử gọi món.',
      combos: 'Hiển thị combo',
      combosDesc: 'Hiển thị khu vực combo ở đầu menu khách hàng.',
    },
    operation: {
      title: 'Vận hành',
      subtitle: 'Điều khiển giờ mở cửa, nhận đơn và luồng xử lý tại bếp.',
      hoursTitle: 'Giờ vận hành',
      availabilityTitle: 'Trạng thái nhận đơn',
      workflowTitle: 'Luồng xử lý đơn',
      openingTime: 'Giờ mở cửa',
      openingTimeHelp: 'Thông tin giờ mở cửa hiển thị ở các giao diện có hỗ trợ.',
      closingTime: 'Giờ đóng cửa',
      closingTimeHelp: 'Có thể đặt giờ đóng cửa qua đêm.',
      orderingEnabled: 'Nhận đơn từ khách',
      orderingEnabledDesc: 'Khi tắt, khách vẫn xem menu nhưng không thể gửi đơn mới.',
      maintenanceMode: 'Chế độ bảo trì',
      maintenanceModeDesc: 'Tạm khóa trải nghiệm đặt món trong thời gian bảo trì.',
      autoConfirm: 'Tự động xác nhận đơn QR',
      autoConfirmDesc: 'Đơn mới từ khách chuyển thẳng sang trạng thái đang phục vụ.',
      overdueThreshold: 'Cảnh báo bếp sau (phút)',
      overdueThresholdHelp: 'Món chưa hoàn thành quá thời gian này sẽ được đánh dấu trễ.',
    },
    bill: {
      title: 'Hóa đơn',
      subtitle: 'Tùy chỉnh nội dung và hành vi in bill sau thanh toán.',
      contentTitle: 'Nội dung hóa đơn',
      behaviorTitle: 'Khổ giấy & hành vi',
      titleLabel: 'Tiêu đề hóa đơn',
      titleHelp: 'Dòng tiêu đề nổi bật phía trên thông tin đơn.',
      footer: 'Lời nhắn cuối hóa đơn',
      footerHelp: 'Thông điệp cảm ơn hoặc thông tin ngắn gửi khách.',
      paperSize: 'Khổ giấy',
      paperSizeHelp: 'Chọn chiều rộng máy in nhiệt đang sử dụng.',
      showWifi: 'Hiển thị WiFi trên bill',
      showWifiDesc: 'In tên WiFi ở cuối hóa đơn khi quán đã cấu hình.',
      autoPrint: 'Tự mở bill sau thanh toán',
      autoPrintDesc: 'Tự mở cửa sổ in sau khi thanh toán thành công.',
    },
    notifications: {
      title: 'Thông báo',
      subtitle: 'Chọn các sự kiện nghiệp vụ được phép phát âm báo trên thiết bị.',
      eventsTitle: 'Sự kiện phát cảnh báo',
      newOrder: 'Đơn hàng mới',
      newOrderDesc: 'Phát chuông khi luồng đơn hàng có cập nhật mới.',
      payment: 'Thanh toán thành công',
      paymentDesc: 'Phát thông báo khi PayOS xác nhận giao dịch thành công.',
      overdue: 'Món bếp quá hạn',
      overdueDesc: 'Phát cảnh báo khi số món vượt ngưỡng thời gian tăng lên.',
    },
    wifi: {
      title: 'WiFi & mã QR',
      subtitle: 'Sinh QR để khách quét và kết nối WiFi nhanh.',
      detailsTitle: 'Thông tin WiFi',
      previewTitle: 'QR kết nối WiFi',
      ssid: 'Tên WiFi (SSID)',
      ssidHelp: 'Tên mạng WiFi được mã hóa vào QR.',
      password: 'Mật khẩu WiFi',
      passwordHelp: 'Có thể để trống nếu WiFi không đặt mật khẩu.',
      qrLabel: 'QR kết nối WiFi',
      empty: 'Nhập SSID để tạo QR',
    },
    preferences: {
      title: 'Cá nhân hóa',
      subtitle: 'Các tùy chọn này chỉ lưu trên trình duyệt của từng nhân viên.',
      sound: 'Âm thanh thông báo',
      soundDesc: 'Cho phép trình duyệt phát chuông khi có sự kiện được bật.',
      loudSound: 'Âm báo lớn',
      loudSoundDesc: 'Phù hợp cho khu vực bếp hoặc môi trường ồn.',
      darkMode: 'Giao diện tối',
      darkModeDesc: 'Lưu lựa chọn giao diện cho trình duyệt hiện tại.',
      language: 'Ngôn ngữ',
    },
  },
  en: {
    page: {
      title: 'System settings',
      subtitle: 'Configure restaurant, payments, customer menu, operations, bills, and alerts.',
    },
    tabs: {
      restaurant: 'Restaurant',
      payment: 'Payments',
      customerMenu: 'Customer menu',
      operation: 'Operations',
      bill: 'Bills',
      notifications: 'Notifications',
      wifi: 'WiFi & QR',
      preferences: 'Preferences',
    },
    actions: {
      save: 'Save changes',
      uploadLogo: 'Upload logo',
      uploading: 'Uploading',
    },
    success: {
      saved: 'System settings have been updated.',
      logoUploaded: 'Restaurant logo has been updated.',
    },
    errors: {
      load: 'Unable to load settings',
      invalidData: 'Invalid data',
      restaurantNameRequired: 'Restaurant name is required.',
      paymentMethodRequired: 'Enable at least one payment method.',
    },
    restaurant: {
      title: 'Restaurant information',
      subtitle: 'Identity and contact details shown across the system.',
      identityTitle: 'Identity & contact',
      logoTitle: 'Restaurant logo',
      logoEmpty: 'No logo yet',
      displayTitle: 'Display configuration',
      name: 'Restaurant name',
      nameHelp: 'Shown on the customer menu and printed bills.',
      hotline: 'Hotline',
      hotlineHelp: 'Restaurant contact phone number.',
      address: 'Address',
      addressHelp: 'Shown on bills and supported restaurant information areas.',
      email: 'Email',
      emailHelp: 'Internal or public restaurant contact email.',
      currency: 'Currency',
      currencyHelp: 'ISO currency code, such as VND.',
      logoUrl: 'Logo URL',
      logoUrlHelp: 'Paste a public URL or upload a JPEG, PNG, or WebP file up to 5MB.',
      taxPercent: 'Tax (%)',
      taxPercentHelp: 'Saved for supported pricing flows.',
      serviceChargePercent: 'Service charge (%)',
      serviceChargePercentHelp: 'Saved restaurant service charge configuration.',
    },
    payment: {
      title: 'Payments',
      subtitle: 'Control payment methods and PayOS QR expiration.',
      methodsTitle: 'Allowed methods',
      cash: 'Cash payment',
      cashDesc: 'Allow staff to confirm cash payments.',
      online: 'QR / PayOS',
      onlineDesc: 'Allow PayOS bank transfer QR creation.',
      expiryTitle: 'Online payment expiration',
      expiry: 'QR expires after (minutes)',
      expiryHelp: 'Applied to new PayOS transactions, from 1 to 120 minutes.',
    },
    customerMenu: {
      title: 'Customer menu',
      subtitle: 'Choose what appears on the QR ordering page.',
      visibilityTitle: 'Visible content',
      unavailable: 'Show unavailable items',
      unavailableDesc: 'Keep sold-out items visible but disabled.',
      recommendations: 'Show recommendations',
      recommendationsDesc: 'Show contextual and popular menu suggestions.',
      combos: 'Show combos',
      combosDesc: 'Show the combo section above the customer menu.',
    },
    operation: {
      title: 'Operations',
      subtitle: 'Control business hours, ordering, and kitchen workflow.',
      hoursTitle: 'Operating hours',
      availabilityTitle: 'Ordering availability',
      workflowTitle: 'Order workflow',
      openingTime: 'Opening time',
      openingTimeHelp: 'Displayed where operating-hour information is supported.',
      closingTime: 'Closing time',
      closingTimeHelp: 'Overnight closing times are supported.',
      orderingEnabled: 'Accept customer orders',
      orderingEnabledDesc: 'Customers can still browse when ordering is disabled.',
      maintenanceMode: 'Maintenance mode',
      maintenanceModeDesc: 'Temporarily lock customer ordering.',
      autoConfirm: 'Auto-confirm QR orders',
      autoConfirmDesc: 'Move new customer orders directly into serving state.',
      overdueThreshold: 'Kitchen alert after (minutes)',
      overdueThresholdHelp: 'Unfinished items beyond this time are marked overdue.',
    },
    bill: {
      title: 'Bills',
      subtitle: 'Customize printed bill content and behavior.',
      contentTitle: 'Bill content',
      behaviorTitle: 'Paper & behavior',
      titleLabel: 'Bill title',
      titleHelp: 'Prominent heading above the order details.',
      footer: 'Footer message',
      footerHelp: 'A short thank-you or customer message.',
      paperSize: 'Paper size',
      paperSizeHelp: 'Select the thermal printer width.',
      showWifi: 'Show WiFi on bill',
      showWifiDesc: 'Print the WiFi name when configured.',
      autoPrint: 'Open bill after payment',
      autoPrintDesc: 'Automatically open the print window after successful payment.',
    },
    notifications: {
      title: 'Notifications',
      subtitle: 'Choose which business events may play alerts on staff devices.',
      eventsTitle: 'Alert events',
      newOrder: 'New orders',
      newOrderDesc: 'Play an alert when the order stream changes.',
      payment: 'Successful payment',
      paymentDesc: 'Notify when PayOS confirms a payment.',
      overdue: 'Overdue kitchen item',
      overdueDesc: 'Alert when the overdue item count increases.',
    },
    wifi: {
      title: 'WiFi & QR code',
      subtitle: 'Generate a QR code for quick customer WiFi access.',
      detailsTitle: 'WiFi details',
      previewTitle: 'Connection QR',
      ssid: 'WiFi name (SSID)',
      ssidHelp: 'Network name encoded in the QR code.',
      password: 'WiFi password',
      passwordHelp: 'Leave blank for an open network.',
      qrLabel: 'WiFi connection QR',
      empty: 'Enter an SSID to generate QR',
    },
    preferences: {
      title: 'Preferences',
      subtitle: 'These options are stored only in each staff browser.',
      sound: 'Notification sound',
      soundDesc: 'Allow browser sounds for enabled business events.',
      loudSound: 'Loud alert',
      loudSoundDesc: 'Useful in kitchens and noisy environments.',
      darkMode: 'Dark mode',
      darkModeDesc: 'Save the current browser theme.',
      language: 'Language',
    },
  },
};
